package pt.sequoia.standByTool.services;

import com.google.auth.oauth2.GoogleCredentials;
import com.google.auth.oauth2.ServiceAccountCredentials;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import pt.sequoia.standByTool.models.Turn;

import java.io.IOException;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

@Service
public class CalendarService {

    private final RestTemplate restTemplate = new RestTemplate();

    // Method interno para obter o Token do Robô usando o ficheiro JSON
    private String getServiceAccountToken() throws IOException {
        // O ficheiro JSON que descarregaste deve ser renomeado para "calendar-key.json"
        // e colocado na pasta: src/main/resources/
        GoogleCredentials credentials = ServiceAccountCredentials.fromStream(
                        new ClassPathResource("calendar-key.json").getInputStream())
                .createScoped(Collections.singleton("https://www.googleapis.com/auth/calendar.events"));

        credentials.refreshIfExpired();
        return credentials.getAccessToken().getTokenValue();
    }

    public String addTurnToCalendar(Turn turn) {

        try {

            String calendarId = turn.getTurnType().getGoogleCalendarId();

            // fallback caso não exista calendário definido
            if (calendarId == null || calendarId.isBlank()) {
                calendarId = "primary";
            }

            String url = "https://www.googleapis.com/calendar/v3/calendars/"
                    + calendarId
                    + "/events";

            // Token da Service Account
            String token = getServiceAccountToken();

            HttpHeaders headers = new HttpHeaders();
            headers.setBearerAuth(token);
            headers.setContentType(MediaType.APPLICATION_JSON);

            // Evento
            Map<String, Object> event = new HashMap<>();

            event.put(
                    "summary",
                    turn.getTurnType().getName() + ": " + turn.getAssignee().getName()
            );

            event.put(
                    "description",
                    "Turn automatically generated by StandByTool. Accepted by: "
                            + turn.getAssignee().getName()
            );

            // Início
            Map<String, String> start = new HashMap<>();
            start.put("date", turn.getStartTime().toString());
            event.put("start", start);

            // Fim
            Map<String, String> end = new HashMap<>();
            end.put("date", turn.getEndTime().plusDays(1).toString());
            event.put("end", end);

            HttpEntity<Map<String, Object>> request =
                    new HttpEntity<>(event, headers);

            ResponseEntity<Map> response =
                    restTemplate.postForEntity(url, request, Map.class);

            if (response.getStatusCode().is2xxSuccessful()
                    && response.getBody() != null) {

                return (String) response.getBody().get("id");
            }

        } catch (Exception e) {
            System.err.println(
                    "❌ Erro ao sincronizar calendário (Service Account): "
                            + e.getMessage()
            );
        }

        return null;
    }
}