# Web Server Configuration
server.port=${PORT:8081}
server.forward-headers-strategy=framework


# Mudar para 'false' quando quisermos abrir a app a todos os colaboradores
app.launch.assigner-only-mode=false

# Spring Data JPA (Hibernate) configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --------------------------------------------------------
# Google Cloud SQL Connection (IAM AUTHENTICATION)
# --------------------------------------------------------
spring.datasource.url=jdbc:mysql:///standByTool?cloudSqlInstance=time-manager-450009:europe-west1:mcfly&socketFactory=com.google.cloud.sql.mysql.SocketFactory&allowPublicKeyRetrieval=true&useSSL=false&enableIamAuth=true
spring.datasource.username=sql-user
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --------------------------------------------------------
# Google OAuth2 Login
# --------------------------------------------------------
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}