# Web Server Configuration
server.port=${PORT:8080}

# Mudar para 'false' quando quisermos abrir a app a todos os colaboradores
app.launch.assigner-only-mode=true


# Spring Data JPA (Hibernate) configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --------------------------------------------------------
# Google Cloud SQL Connection
# --------------------------------------------------------
# The format must use the Google Socket Factory and your Instance Connection Name
spring.datasource.url=jdbc:mysql:///standByTool?cloudSqlInstance=time-manager-450009:europe-west1:mcfly&socketFactory=com.google.cloud.sql.mysql.SocketFactory&allowPublicKeyRetrieval=true&useSSL=false&enableIamAuth=true
spring.datasource.username=time-manager-450009
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver